# Generated by Django 5.1.1 on 2024-09-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
